//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.12 at 11:20:40 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "http://nure.ua/bookShop",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {
                @XmlNs(prefix = "book", namespaceURI = "http://nure.ua/bookShop")
        })
package ua.nure.bookshop.entity;

import javax.xml.bind.annotation.XmlNs;