<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.service.journaldev.nure.ua/"
             xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://impl.service.journaldev.nure.ua/"
             name="PersonServiceImplService">
    <import namespace="http://service.journaldev.nure.ua/" location="http://localhost:8888/ws/person?wsdl=1"/>
    <binding xmlns:ns1="http://service.journaldev.nure.ua/" name="PersonServiceImplPortBinding"
             type="ns1:PersonService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
        <operation name="getAllPersons">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </output>
        </operation>
        <operation name="getPerson">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </output>
        </operation>
        <operation name="addPerson">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </output>
        </operation>
        <operation name="deletePerson">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="http://service.journaldev.nure.ua/"/>
            </output>
        </operation>
    </binding>
    <service name="PersonServiceImplService">
        <port name="PersonServiceImplPort" binding="tns:PersonServiceImplPortBinding">
            <soap:address location="http://localhost:8888/ws/person"/>
        </port>
    </service>
</definitions>