
package ua.nure.journaldev.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "PersonService", targetNamespace = "http://service.server.journaldev.nure.ua/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface PersonService {

    /**
     * @param arg0
     * @return returns ua.nure.journaldev.client.Person
     */
    @WebMethod
    @WebResult(partName = "return")
    public Person getPerson(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0);

    /**
     * @return returns ua.nure.journaldev.client.PersonArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public PersonArray getAllPersons();

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean deletePerson(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0);

    /**
     * @param arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean addPerson(
            @WebParam(name = "arg0", partName = "arg0")
                    Person arg0);

}
