
package ua.nure.publisher.client.service;

import ua.nure.publisher.client.dto.Magazine;
import ua.nure.publisher.client.dto.Magazines;
import ua.nure.publisher.client.dto.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "MagazinesService", targetNamespace = "http://service.server.publisher.nure.ua/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface MagazinesService {

    /**
     * @param arg0
     */
    @WebMethod
    void removeMagazineById(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0);

    /**
     * @param arg0
     */
    @WebMethod
    void addMagazine(
            @WebParam(name = "arg0", partName = "arg0")
                    Magazine arg0);

    /**
     * @param arg0
     * @return returns ua.nure.publisher.client.Magazine
     */
    @WebMethod
    @WebResult(partName = "return")
    Magazine getMagazineById(
            @WebParam(name = "arg0", partName = "arg0")
                    int arg0);

    /**
     *
     */
    @WebMethod
    void clearMagazines();

    /**
     * @return returns ua.nure.publisher.client.Magazines
     */
    @WebMethod
    @WebResult(partName = "return")
    Magazines getMagazines();

}
